# Generated by Django 2.2.2 on 2019-06-30 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('node_name', models.CharField(max_length=50, verbose_name='Chave')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Probabilidade')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Número')),
                ('content', models.TextField(max_length=255, verbose_name='Conteúdo')),
                ('publications', models.ManyToManyField(to='knowledge_modeling.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=50, verbose_name='Conteúdo')),
                ('number', models.CharField(max_length=5, null=True, verbose_name='Número')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='knowledge_modeling.Question')),
            ],
        ),
    ]
