# Generated by Django 2.2.2 on 2019-06-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_modeling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='publications',
            new_name='subjects',
        ),
    ]
