# Generated by Django 2.2.2 on 2019-07-04 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_modeling', '0002_auto_20190630_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.IntegerField(default=1, null=True, verbose_name='Nivel'),
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Probabilidade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='knowledge_modeling.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
