# Generated by Django 2.2.2 on 2019-07-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_modeling', '0004_auto_20190705_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubject',
            name='value',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Probabilidade'),
        ),
    ]
