# Generated by Django 2.2.2 on 2019-09-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_modeling', '0005_auto_20190705_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('correct_knowing', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Acerta-Sabendo')),
                ('correct_not_knowing', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Acerta-Não-Sabendo')),
                ('mistake_knowing', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Erra-Sabendo')),
                ('mistake_not_knowing', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Erra-Não-Sabendo')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='knowledge_modeling.Difficulty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='knowledge_modeling.Subject')),
            ],
        ),
    ]
