# Generated by Django 2.2.2 on 2019-10-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_modeling', '0007_subject_publications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='publications',
        ),
        migrations.AddField(
            model_name='subject',
            name='parents',
            field=models.ManyToManyField(related_name='_subject_parents_+', to='knowledge_modeling.Subject'),
        ),
    ]
