# Generated by Django 2.2.2 on 2019-10-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_modeling', '0008_auto_20191002_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, related_name='_subject_parents_+', to='knowledge_modeling.Subject'),
        ),
    ]
