# Generated by Django 2.2.2 on 2019-10-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_modeling', '0009_auto_20191002_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='parents',
        ),
        migrations.AddField(
            model_name='subject',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='_subject_children_+', to='knowledge_modeling.Subject'),
        ),
    ]
