# Generated by Django 2.2.2 on 2019-10-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_modeling', '0010_auto_20191002_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='knowledge_modeling.Subject'),
        ),
    ]
