# Generated by Django 2.2.2 on 2019-10-02 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_modeling', '0011_auto_20191002_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='children',
            field=models.ManyToManyField(blank=True, to='knowledge_modeling.Subject'),
        ),
        migrations.CreateModel(
            name='SimpleEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('correct_knowing', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Acerta-Sabendo')),
                ('correct_not_knowing', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Acerta-Não-Sabendo')),
                ('mistake_knowing', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Erra-Sabendo')),
                ('mistake_not_knowing', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Erra-Não-Sabendo')),
                ('children', models.ManyToManyField(blank=True, to='knowledge_modeling.SimpleEvidence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObservableEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('correct_knowing', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Acerta-Sabendo')),
                ('correct_not_knowing', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Acerta-Não-Sabendo')),
                ('mistake_knowing', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Erra-Sabendo')),
                ('mistake_not_knowing', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Erra-Não-Sabendo')),
                ('children', models.ManyToManyField(blank=True, to='knowledge_modeling.ObservableEvidence')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observable_evidences', to='knowledge_modeling.Difficulty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
