# Generated by Django 2.2.2 on 2019-10-09 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_modeling', '0013_questionevidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Probabilidade')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='knowledge_modeling.Evidence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='simpleevidence',
            name='children',
        ),
        migrations.AlterField(
            model_name='questionevidence',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='knowledge_modeling.Evidence'),
        ),
        migrations.AlterField(
            model_name='questionevidence',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='knowledge_modeling.Question'),
        ),
        migrations.DeleteModel(
            name='ObservableEvidence',
        ),
        migrations.DeleteModel(
            name='SimpleEvidence',
        ),
    ]
