# Generated by Django 2.2.2 on 2019-10-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_modeling', '0014_auto_20191009_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevidence',
            name='value',
        ),
        migrations.AddField(
            model_name='userevidence',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
