# Generated by Django 2.2.2 on 2019-10-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_modeling', '0015_auto_20191009_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevidence',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='knowledge_modeling.QuestionEvidence'),
        ),
    ]
