# Generated by Django 2.2.2 on 2020-05-31 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('children', models.ManyToManyField(blank=True, to='its.Evidence')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Número')),
                ('content', models.TextField(max_length=255, verbose_name='Conteúdo')),
                ('evidences', models.ManyToManyField(to='its.Evidence')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('children', models.ManyToManyField(blank=True, to='its.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slice', models.IntegerField(default=0, verbose_name='Índice de Tempo')),
                ('false_value', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Probabilidade Falsa')),
                ('true_value', models.DecimalField(decimal_places=10, default=0, max_digits=10, verbose_name='Probabilidade Verdadeira')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='its.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slice', models.IntegerField(default=0, verbose_name='Expansão no Tempo')),
                ('observations', models.CharField(default='', max_length=255, verbose_name='Observações')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='its.Evidence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_questions', to='its.Course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_courses', to='its.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slice', models.IntegerField(default=0, verbose_name='Expansão no Tempo')),
                ('observations', models.CharField(default='', max_length=255, verbose_name='Observações')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_evidences', to='its.Evidence')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='its.Evidence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_evidences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='its.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidences', models.ManyToManyField(to='its.Evidence')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='its.Network')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='its.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='CourseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='its.Course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='its.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=50, verbose_name='Conteúdo')),
                ('number', models.CharField(max_length=5, null=True, verbose_name='Número')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='its.Question')),
            ],
        ),
    ]
