# Generated by Django 2.2.2 on 2020-05-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='children',
            new_name='subjects',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='children',
        ),
        migrations.AddField(
            model_name='subject',
            name='evidences',
            field=models.ManyToManyField(to='its.Evidence'),
        ),
    ]
