# Generated by Django 2.2.2 on 2020-05-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0002_auto_20200531_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
        migrations.AddField(
            model_name='coursequestion',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='evidences',
            field=models.ManyToManyField(blank=True, to='its.Evidence'),
        ),
    ]
