# Generated by Django 2.2.2 on 2020-05-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0003_auto_20200531_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição'),
        ),
    ]
