# Generated by Django 2.2.2 on 2020-05-31 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0004_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequestion',
            name='network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_questions', to='its.Network'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercoursequestion',
            name='network',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_courses_questions', to='its.Network'),
            preserve_default=False,
        ),
    ]
