# Generated by Django 2.2.2 on 2020-05-31 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0005_auto_20200531_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='network',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='its.Network'),
            preserve_default=False,
        ),
    ]
