# Generated by Django 2.2.2 on 2020-05-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0006_course_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursequestion',
            name='network',
        ),
    ]
