# Generated by Django 2.2.2 on 2020-05-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0007_remove_coursequestion_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completo'),
        ),
    ]
