# Generated by Django 2.2.2 on 2020-05-31 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0008_usercourse_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_courses', to='its.CourseQuestion'),
        ),
    ]
