# Generated by Django 2.2.2 on 2020-06-04 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0009_auto_20200531_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoursequestion',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercoursequestion',
            name='question',
        ),
        migrations.AddField(
            model_name='usercoursequestion',
            name='course_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_questions', to='its.CourseQuestion'),
            preserve_default=False,
        ),
    ]
