# Generated by Django 2.2.2 on 2020-06-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0010_auto_20200604_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='evidences',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subjects',
        ),
    ]
