# Generated by Django 2.2.2 on 2020-06-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0011_auto_20200604_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksubject',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='its.Subject'),
        ),
    ]
