# Generated by Django 2.2.2 on 2020-06-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0013_auto_20200604_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='evidences',
            field=models.ManyToManyField(blank=True, to='its.Node'),
        ),
    ]
