# Generated by Django 2.2.2 on 2020-06-04 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0014_auto_20200604_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.RemoveField(
            model_name='usercourseevidence',
            name='node',
        ),
        migrations.RemoveField(
            model_name='userevidence',
            name='node',
        ),
        migrations.RemoveField(
            model_name='usersubject',
            name='node',
        ),
        migrations.AddField(
            model_name='usercourseevidence',
            name='evidence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='its.Evidence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userevidence',
            name='evidence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_evidences', to='its.Evidence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networksubject',
            name='evidences',
            field=models.ManyToManyField(related_name='networks_subjects_evidences', to='its.Evidence'),
        ),
        migrations.AlterField(
            model_name='networksubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks_subjects', to='its.Subject'),
        ),
        migrations.AlterField(
            model_name='networksubject',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='networks_subjects_parents', to='its.Subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='evidences',
            field=models.ManyToManyField(blank=True, to='its.Evidence'),
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.AddField(
            model_name='usersubject',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_subjects', to='its.Subject'),
            preserve_default=False,
        ),
    ]
