# Generated by Django 2.2.2 on 2020-06-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0015_auto_20200604_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networksubject',
            old_name='subjects',
            new_name='network_subjects',
        ),
    ]
