# Generated by Django 3.1.2 on 2020-11-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0016_auto_20200605_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursequestion',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users_questions', to='its.course'),
        ),
    ]
