# Generated by Django 3.1.2 on 2020-11-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0017_usercoursequestion_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoursequestion',
            name='course',
        ),
    ]
