# Generated by Django 3.1.2 on 2020-12-19 19:14

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0019_usercoursequestion_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSubjectProbabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects_probabilities', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('evidences_probabilities', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('transition_probabilities', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('network_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probabilities', to='its.networksubject')),
            ],
        ),
    ]
